### ISSUE TITLE
Add cron script to run the bot every day.

### ISSUE THREAD

**Issue by zorroblue** [metakgp/chitragupta#4]
Add a small shell script to run the bot on a daily basis.

**Comment by vchrombie** [comment]
Hello,
Myself, Venu 

I have a doubt regarding this issue.

Do we need to write a shell script such that the bot runs everyday?

**Comment by zorroblue** [comment]
Yes @vchrombie

**Comment by SubhrajitPrusty** [comment]
Added a bash script to solve this. #5 
Used a `while` loop, instead of `crontab`, or `at`. Is that okay?

**Comment by icyflame** [comment]
@zorroblue I am not sure if a script is absolutely necessary, adding this crontab template to readme should be enough,

```sh
86400 * * * * cd /path/ && python chitragupta.py
```

**Comment by zorroblue** [comment]
@icyflame Agreed, this would be better. 

@SubhrajitPrusty If you don't mind, can you edit your PR to just make changes to the README?

**Comment by SubhrajitPrusty** [comment]
#6 should be okay. @zorroblue can you check?
